### ISSUE TITLE
Test module falling after installation

### ISSUE THREAD

**Issue by geboro** [jessieren/DeepVirFinder#38]
DeepVirFinder isn't working in Ubuntu 20.04 after installing dependencies succesfully... 

```
(dvf)$ python dvf.py -i ./test/crAssphage.fa -o ./test/ -l 300
Using Theano backend.
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
1. Loading Models.
   model directory /raw_data/DeepVirFinder/models
Traceback (most recent call last):
  File "dvf.py", line 131, in <module>
    modDict[contigLengthk] = load_model(os.path.join(modDir, modName))
  File "/opt/anaconda/envs/dvf/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/opt/anaconda/envs/dvf/lib/python3.6/site-packages/keras/engine/saving.py", line 224, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

and after installing mkl-service... 

```
(dvf) $ conda install mkl-service
(dvf) $ python3.6 dvf.py -i ./test/crAssphage.fa -o ./test/ -l 300
Using Theano backend.
1. Loading Models.
   model directory /soft/DeepVirFinder/models
Traceback (most recent call last):
  File "dvf.py", line 131, in <module>
    modDict[contigLengthk] = load_model(os.path.join(modDir, modName))
  File "/opt/anaconda/envs/dvf/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/opt/anaconda/envs/dvf/lib/python3.6/site-packages/keras/engine/saving.py", line 224, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

```

Any idea of what's going on here?

**Comment by del-oxyribonucleic-acid** [comment]
I am having the same issue!

**Comment by TomasaSbaffi** [comment]
I also have the same issue, I am trying to install the packages in different orders but with no actual rationale behind. 
It should be due to issues with dependencies: 
https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi

**Comment by TomasaSbaffi** [comment]
I solved it with the following:

conda activate dvf
pip3 uninstall keras
pip3 uninstall tensorflow
pip3 uninstall h5py

pip3 install 'h5py==2.10.0' --force-reinstall
pip3 install 'tensorflow==2.4.1'
pip3 install 'keras==2.2.4'

I do believe the real problem for me was the version of TF, the older version installed with the instructions given was not working nor the new versions, but a middle ground version did work. 
h5py and keras are reinstalled as per instructions so I am not sure if uninstalling them and re installing them actually helped.
I still do not know why but this worked fine for me. I hope it helps.

**Comment by fluhus** [comment]
Thanks @TomasaSbaffi, your response helped me solve the issue. Reinstalling h5py with the version you mentioned was enough in my case.

@jessieren perhaps the instructions for creating the conda env should be updated with `h5py==2.10.0`?
